name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - xcode: "26.0"
            deployment_target: ""
    runs-on: macos-26
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        xcodebuild -version
        
    - name: Get app version
      run: |
        # Build the project first to generate the app bundle
        xcodebuild -project VocalText.xcodeproj \
          -scheme VocalText \
          -configuration Release \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=NO
          
        # Get the app version from the project
        APP_VERSION=$(defaults read "$PWD/DerivedData/Build/Products/Release/VocalText.app/Contents/Info.plist" CFBundleShortVersionString)
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "App version: $APP_VERSION"
    
    - name: Create build artifacts directory
      run: mkdir -p build-artifacts
    
    - name: Copy app bundle to artifacts directory
      run: |
        cp -R DerivedData/Build/Products/Release/VocalText.app build-artifacts/
    
    - name: Create ZIP archive
      run: |
        cd build-artifacts
        zip -r "VocalText-${{ env.APP_VERSION }}.zip" "VocalText.app"
    
    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v4
      with:
        name: VocalText-${{ env.APP_VERSION }}.zip
        path: build-artifacts/VocalText-${{ env.APP_VERSION }}.zip